In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("healthcare_dataset.csv")

In [2]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [4]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [5]:
df.shape

(55500, 15)

In [6]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [7]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [8]:
df.duplicated().sum()

534

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.duplicated().sum()

0

In [11]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [12]:
df.columns

Index(['name', 'age', 'gender', 'blood_type', 'medical_condition',
       'date_of_admission', 'doctor', 'hospital', 'insurance_provider',
       'billing_amount', 'room_number', 'admission_type', 'discharge_date',
       'medication', 'test_results'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                54966 non-null  object
 1   age                 54966 non-null  int64
 2   gender              54966 non-null  object
 3   blood_type          54966 non-null  object
 4   medical_condition   54966 non-null  object
 5   date_of_admission   54966 non-null  object
 6   doctor              54966 non-null  object
 7   hospital            54966 non-null  object
 8   insurance_provider  54966 non-null  object
 9   billing_amount      54966 non-null  float64
 10  room_number         54966 non-null  int64
 11  admission_type      54966 non-null  object
 12  discharge_date      54966 non-null  object
 13  medication          54966 non-null  object
 14  test_results        54966 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.7+ MB

In [14]:
df['date_of_admission'] = pd.to_datetime(df['date_of_admission'])

In [15]:
df['discharge_date'] = pd.to_datetime(df['discharge_date'])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                54966 non-null  object
 1   age                 54966 non-null  int64
 2   gender              54966 non-null  object
 3   blood_type          54966 non-null  object
 4   medical_condition   54966 non-null  object
 5   date_of_admission   54966 non-null  datetime64[ns]
 6   doctor              54966 non-null  object
 7   hospital            54966 non-null  object
 8   insurance_provider  54966 non-null  object
 9   billing_amount      54966 non-null  float64
 10  room_number         54966 non-null  int64
 11  admission_type      54966 non-null  object
 12  discharge_date      54966 non-null  datetime64[ns]
 13  medication          54966 non-null  object
 14  test_results        54966 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.7+ MB

In [17]:
df.fillna("Unknown", inplace=True)
df['doctor'].fillna('Unknown', inplace=True)
df['billing_amount'].fillna(
    df['billing_amount'].median(),
    inplace=True
)

In [18]:
df.isnull().sum()

name                  0
age                   0
gender                0
blood_type            0
medical_condition     0
date_of_admission     0
doctor                0
hospital              0
insurance_provider    0
billing_amount        0
room_number           0
admission_type        0
discharge_date        0
medication            0
test_results          0
dtype: int64

In [19]:
Q1 = df['billing_amount'].quantile(0.25)
Q3 = df['billing_amount'].quantile(0.75)

IQR = Q3 - Q1

In [20]:
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [21]:
outliers = df[
    (df['billing_amount'] < lower) |
    (df['billing_amount'] > upper)
]

In [22]:
outliers.shape

(0, 15)

In [23]:
df = df[
    (df['billing_amount'] >= lower) &
    (df['billing_amount'] <= upper)
]

In [24]:
df.shape

(54966, 15)

In [25]:
df.info()
df.isnull().sum()
df.duplicated().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                54966 non-null  object
 1   age                 54966 non-null  int64
 2   gender              54966 non-null  object
 3   blood_type          54966 non-null  object
 4   medical_condition   54966 non-null  object
 5   date_of_admission   54966 non-null  datetime64[ns]
 6   doctor              54966 non-null  object
 7   hospital            54966 non-null  object
 8   insurance_provider  54966 non-null  object
 9   billing_amount      54966 non-null  float64
 10  room_number         54966 non-null  int64
 11  admission_type      54966 non-null  object
 12  discharge_date      54966 non-null  datetime64[ns]
 13  medication          54966 non-null  object
 14  test_results        54966 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.7+ MB

,age,date_of_admission,billing_amount,room_number,discharge_date
count,54966.000000,54966,54966.000000,54966.000000,54966
mean,51.535185,2021-11-01 17:35:29.505512448,25544.306284,301.124404,2021-11-17 05:34:28.202161408
min,13.000000,2019-05-08 00:00:00,-2008.492140,101.000000,2019-05-09 00:00:00
25%,35.000000,2020-07-28 00:00:00,13243.718641,202.000000,2020-08-13 00:00:00
50%,52.000000,2021-11-02 00:00:00,25542.749145,302.000000,2021-11-18 00:00:00
75%,68.000000,2023-02-03 00:00:00,37819.858159,401.000000,2023-02-19 00:00:00
max,89.000000,2024-05-07 00:00:00,52764.276736,500.000000,2024-06-06 00:00:00
std,19.605661,NaN,14208.409711,115.223143,NaN

In [26]:
df.to_csv(
    "cleaned_healthcare_dataset.csv",
    index=False
)